### ISSUE TITLE
Generating 1408x1408 images on my 3080

### ISSUE THREAD

**Issue by Grimig** [harskish/sdui#4]
By lowering the Attn. group size to "1" im able to generate 1408x1408 images on my 3080 locally, and the results are amazing.
 Im not sure how youve done it, but other repos ive tried cant come close.
 
 Thought id give you a heads up if you weren't aware.

**Comment by harskish** [comment]
Glad you're finding the project useful!
While I've tweaked VRAM usage in other ways, I can't take any credit for the attn. group slicing specifically, it was first described here: https://github.com/basujindal/stable-diffusion/pull/117#issuecomment-1236387342.

**Comment by Kallamamran** [comment]
"the results are amazing"
Are they really? The higher I go above 512, in any dimension, the more the model messes up and starts adding strange things (or anatomy) to the picture. I thought rendering at higher resolution would be great, but now I don't know. It feels like we really need a model trained on higher resolution images or a model that diffuses in a new way(???)

**Comment by harskish** [comment]
I do tend to agree. Images with repeating patterns such as landscapes look pretty good at high resolutions, but single objects with defined structures (faces etc.) often become nonsensical. Generating in 512x512 and using img2img to go to higher resolutions seems to work better though.

**Comment by Kallamamran** [comment]
Yeah. It's interesting to make 1920x512 images of a celebrity portrait though. You often get 3-4 good and different poses of the same person :)
