### ISSUE TITLE
Run-time error on MacOS 12.6: symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)

### ISSUE THREAD

**Issue by whab** [harskish/sdui#5]
OS: MacOS 12.6
Hardware: MacBookPro M1 Pro

I get the following error when running "python interactive.py" after installing for macOS as instructed:

ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/ldm/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x000A): symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)

Any idea? Thanks!

**Comment by harskish** [comment]
Looks like this issue: https://github.com/protocolbuffers/protobuf/issues/10571

**Comment by whab** [comment]
Thanks! As suggested in the linked issue, downgrading protobuf seems to solve the issue, eg:

pip3 install protobuf==3.19.4
